### ISSUE TITLE
heavy composer package with uneeded files

### ISSUE THREAD

**Issue by francescolaffi** [martin-georgiev/postgresql-for-doctrine#107]
I noticed this package ends up being on the heavy side as it also ships development tools such as two versions of local-php-security-checker that gets installed by composer

Packages usually define excluded files from the packages, leaving only what is needed for runtime, to avoid wasting network/disk resources :
- with .gitattributes, e.g. see doctrine: https://github.com/doctrine/dbal/blob/3.3.x/.gitattributes
- with composer archive exclusion: https://getcomposer.org/doc/04-schema.md#archive 

Thanks

**Comment by martin-georgiev** [comment]
Good call! Thanks for reminding me about it.

**Comment by martin-georgiev** [comment]
Fix for this is now merged into `master` and will be included with the tag for the next minor release.
