### ISSUE TITLE
How to use TO_JSON with JSON_GET_FIELD_AS_TEXT

### ISSUE THREAD

**Issue by dmitryuk** [martin-georgiev/postgresql-for-doctrine#113]
I want to get sql like `select (np.params::json)->> 'slug'`, `np.params` is a text field

DDL:
```sql
JSON_GET_FIELD_AS_TEXT(TO_JSON(np.params), 'slug')
```

Finally got an error:
`Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col 110: Error: Expected Doctrine\ORM\Query\Lexer::T_INPUT_PARAMETER, got 'np'
`
What I do wrong?

**Comment by martin-georgiev** [comment]
Shall be resolved with the release of #116
