### ISSUE TITLE
support symfony 4

### ISSUE THREAD

**Issue by Gemorroj** [martin-georgiev/postgresql-for-doctrine#12]
What about `Symfony4` support?

**Comment by martin-georgiev** [comment]
Are you aware of any sf4 issues? I don't believe there are any blockers for using the package with sf4. This is not a bundle and it doesn't have any Symfony dependencies.

**Comment by Gemorroj** [comment]
I haven't tried to install the library in Symfony 4 yet.
Just in the [README](/martin-georgiev/postgresql-for-doctrine#integration-with-symfony-v2-and-v3) provided only Symfony 2 and 3.

**Comment by martin-georgiev** [comment]
I've updated the README file so it is more obvious that the package can be used with any modern version of Symfony.
Thanks for bringing this matter to my attention @Gemorroj
