### ISSUE TITLE
Jsonb::convertToPHPValue(): Return value must be of type array|string|int|float|null, bool returned

### ISSUE THREAD

**Issue by Gemorroj** [martin-georgiev/postgresql-for-doctrine#129]
after upgrade to https://github.com/martin-georgiev/postgresql-for-doctrine/releases/tag/v2.0.0
```
Uncaught PHP Exception TypeError: "MartinGeorgiev\Doctrine\DBAL\Types\Jsonb::convertToPHPValue(): Return value must be of type array|string|int|float|null, bool returned
```
[`JsonTransformer::transformToPostgresJson`](https://github.com/martin-georgiev/postgresql-for-doctrine/blob/v2.0.0/src/MartinGeorgiev/Doctrine/DBAL/Types/JsonTransformer.php#L34) may return bool value.

**Comment by martin-georgiev** [comment]
Can you please share the data that you are trying to transform?
The shared information needs to be more specific to debug the problem and add reasonable test scenarios for this regression.

**Comment by martin-georgiev** [comment]
Addressed in https://github.com/martin-georgiev/postgresql-for-doctrine/pull/131
