### ISSUE TITLE
problem with null

### ISSUE THREAD

**Issue by gareth-ib** [martin-georgiev/postgresql-for-doctrine#17]
this line would be a problem with array entries that are null, which is valid for the postgres arrays

https://github.com/martin-georgiev/postgresql-for-doctrine/blob/6267c5693218e3ac1d0cecb6ff65ecb6e279ea78/src/MartinGeorgiev/Doctrine/DBAL/Types/SmallIntArray.php#L32

**Comment by martin-georgiev** [comment]
You're right, this will be a problem when a `null` value is given. Issue needs addressing.
However, if I'm not mistaken this situation can happen only when some data manipulation happened and was persisted through another, non-Doctrine process. When transforming from PHP value to PostgreSQL array item, `SmallIntArray::isValidArrayItemForDatabase` will complain about non-integer-like values.

**Comment by pursehouse** [comment]
yes, all the lines validating the array data need updating

**Comment by martin-georgiev** [comment]
Do you mind opening new MR addressing the issue?

**Comment by gareth-ib** [comment]
I don't have time to work on a fix right now, was just pointing out a fix that's in need.
you might be able to remove your json stuff too, cuz doctrine added some level of json to their core now

**Comment by martin-georgiev** [comment]
It's a shame this project gets almost none community contributions :(

**Comment by gareth-ib** [comment]
yeah that's a shame. I'm just looking for options right now and noticed that issue, not using this yet.
But the fact it takes so much copy/paste to get it working definitely scares people off from using this. Might wanna figure out how to get it to auto-enable just from the composer require. Like laravel's auto discover in 5.5+, or maybe a minor line but that giant block to put into config is killer

**Comment by gareth-ib** [comment]
for sure those config options per package should be a version controlled file per-framework, not just giant text

**Comment by martin-georgiev** [comment]
The issue is now addressed with the release of [v0.11](https://github.com/martin-georgiev/postgresql-for-doctrine/pull/20).
