### ISSUE TITLE
Add support for DBAL v4

### ISSUE THREAD

**Issue by adrianrudnik** [martin-georgiev/postgresql-for-doctrine#182]
See the [release statement](https://www.doctrine-project.org/2024/02/03/doctrine-orm-3-and-dbal-4-released.html).

Current version can't be required by a default symfony [webapp](https://symfony.com/doc/current/setup.html#creating-symfony-applications) installation.

**Comment by adrianrudnik** [comment]
It breaks mostly in every usage of `Lexer::*` constants, like `Lexer::T_IDENTIFIER`. The enumerated types where moved to an enum declared `\Doctrine\ORM\Query\TokenType`, like `\Doctrine\ORM\Query\TokenType::T_IDENTIFIER`.

**Comment by martin-georgiev** [comment]
I believe https://github.com/martin-georgiev/postgresql-for-doctrine/releases/tag/v2.4.0 addressed the described issue.

**Comment by martin-georgiev** [comment]
Released in https://github.com/martin-georgiev/postgresql-for-doctrine/releases/tag/v2.4.1
