### ISSUE TITLE
InArray use ANY instead of ANY_OF

### ISSUE THREAD

**Issue by landure** [martin-georgiev/postgresql-for-doctrine#200]
`MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\InArray` use `MartinGeorgiev\Doctrine\ORM\Query\AST\Functions\Any` by calling `ANY` as function name.

The documentation examples use `ANY_OF` as alias for the Any function, triggering a type error when using InArray.

Either detect the alias used for `Any` class (prefered), or use `ANY_OF` (breaking change for code already using `InArray`).

Thank you for your work.

**Comment by martin-georgiev** [comment]
Please provide code snippets to replicate the issue.

**Comment by landure** [comment]
My bad, i'm an idiot.
