### ISSUE TITLE
Support || operator

### ISSUE THREAD

**Issue by samdark** [martin-georgiev/postgresql-for-doctrine#221]
Would be great to have support for string concatenation `||` operator to generating queries like:

```sql
SELECT *
FROM report
WHERE title || code || content ILIKE '%mysearch%';
```

It is preferred to `CONCAT()` in order to use a trigram gin index for ILIKE: https://niallburkley.com/blog/index-columns-for-like-in-postgres/

**Comment by martin-georgiev** [comment]
Nice idea, would you mind helping with implementation? Here is a blueprints of how simple this may look like: [example](https://github.com/martin-georgiev/postgresql-for-doctrine/pull/170/files)

**Comment by samdark** [comment]
Yes, will try it.

**Comment by samdark** [comment]
@martin-georgiev done.

**Comment by samdark** [comment]
Anything else needed?

**Comment by samdark** [comment]
Thanks. How about release?

**Comment by martin-georgiev** [comment]
> Thanks. How about release?

https://github.com/martin-georgiev/postgresql-for-doctrine/releases/tag/v2.6.0

Enjoy 😊

**Comment by samdark** [comment]
Thank you!
