### ISSUE TITLE
Example  for ILIKE, ANY_OF, IS_CONTAINED_BY, to pretend problem as in #33

### ISSUE THREAD

**Issue by llaakkkk** [martin-georgiev/postgresql-for-doctrine#44]
#33 - There was a problem with using ILIKE function, I also had the same problem with ANY_OF, IS_CONTAINED_BY, so it will great to add a page like `code_to_inspire.md` and add there live examples. 
I have some example there https://speakerdeck.com/llaakkkk/what-ive-learnt-after-starting-to-work-with-symfony-and-postgresql?slide=13

**Comment by martin-georgiev** [comment]
Resolved via #45
