### ISSUE TITLE
Add aggregate functions

### ISSUE THREAD

**Issue by hason** [martin-georgiev/postgresql-for-doctrine#55]
https://www.postgresql.org/docs/current/functions-aggregate.html

- [array_agg](https://gitlab.webmozarts.com/webmozarts/data-doctrine-orm-bundle/blob/master/Func/Postgresql/String/ArrayAgg.php)
- json_agg
- jsonb_agg
- json_object_agg
- jsonb_object_agg
- string_agg
- xmlagg

**Comment by martin-georgiev** [comment]
Would you like to contribute to the project? It is really not very complex and the recent #56 PR from @strider2038 can be used as a guiding example.

**Comment by martin-georgiev** [comment]
Draft PR prepared in #63
