### ISSUE TITLE
Feature: add SIMILAR TO functions

### ISSUE THREAD

**Issue by strider2038** [martin-georgiev/postgresql-for-doctrine#57]
Suggesting to add support for `SIMILAR TO` and `NOT SIMILAR TO` functions

See doc https://www.postgresql.org/docs/9.6/functions-matching.html
Pull request https://github.com/martin-georgiev/postgresql-for-doctrine/pull/56

**Comment by martin-georgiev** [comment]
This is now supported from version [1.3.0](https://github.com/martin-georgiev/postgresql-for-doctrine/tree/v1.3.0) onwards.
