### ISSUE TITLE
Bug: stored JSON value may be integer/float/string

### ISSUE THREAD

**Issue by strider2038** [martin-georgiev/postgresql-for-doctrine#58]
We are storing variable type of data in JSONB field. It can be object, integer, float or string. So we have an issue with Jsonb and primitive types. I think array type must be removed from these methods.

https://github.com/martin-georgiev/postgresql-for-doctrine/blob/master/src/MartinGeorgiev/Doctrine/DBAL/Types/Jsonb.php#L45
https://github.com/martin-georgiev/postgresql-for-doctrine/blob/master/src/MartinGeorgiev/Doctrine/DBAL/Types/JsonTransformer.php#L33

**Comment by martin-georgiev** [comment]
Can you share an example with the actual outcome and the expected one?

**Comment by strider2038** [comment]
JSON is not always objects or arrays. String or numeric values are valid JSON too. So this code

```php
json_decode("\"string\"", true);
```

returns string result and leads to type exception here https://github.com/martin-georgiev/postgresql-for-doctrine/blob/master/src/MartinGeorgiev/Doctrine/DBAL/Types/JsonTransformer.php#L33.

**Comment by martin-georgiev** [comment]
@strider2038 do you mind confirming the changes in #66 will fix the use-case you have?

**Comment by strider2038** [comment]
> @strider2038 do you mind confirming the changes in #66 will fix the use-case you have?

Yes, this solves our issue. Thanks.

**Comment by martin-georgiev** [comment]
Cool, it is released in the last version published for Composer.
