### ISSUE TITLE
Add CAST function

### ISSUE THREAD

**Issue by Gemorroj** [martin-georgiev/postgresql-for-doctrine#86]
probable realization same as mysql https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Mysql/Cast.php

**Comment by martin-georgiev** [comment]
It will be truly awesome when you can help with a PR for it :). I'll make sure to review and release promptly.

**Comment by martin-georgiev** [comment]
Once #116 is updated & merged, this will be addressed.

**Comment by martin-georgiev** [comment]
#116 addresses this and it is now merged into `main`. `CAST` will make it in the upcoming release (v2.0.0).
