### ISSUE TITLE
CONTAINS Function

### ISSUE THREAD

**Issue by pegase23** [martin-georgiev/postgresql-for-doctrine#9]

**Comment by martin-georgiev** [comment]
I guess you managed to resolve your issue. From the looks of it, you were mixing an integer array with a string array.

**Comment by pegase23** [comment]
Effectively,
it was a problem of type.
Thank you for the quick response


Le 19 déc. 2017 14:46, "Martin Georgiev" <notifications@github.com> a
écrit :

I guess you managed to resolve your issue. From the looks of it, you were
mixing an integer array with a string array.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/martin-georgiev/postgresql-for-doctrine/issues/9#issuecomment-352754737>,
or mute the thread
